version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=paul@cybertowel.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"  # Volume for SSL certificates
    labels:
      - "traefik.enable=true"
      # Define the redirect middleware globally (optional)
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # Traefik dashboard router
      - "traefik.http.routers.traefik.rule=Host(`traefik.kanjer.api.backend.engineering`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"

  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    labels:
      - "traefik.enable=true"
      # HTTPS router
      - "traefik.http.routers.webserver-secure.rule=Host(`kanjer.api.backend.engineering`)"
      - "traefik.http.routers.webserver-secure.entrypoints=websecure"
      - "traefik.http.routers.webserver-secure.tls.certresolver=myresolver"
      - "traefik.http.services.webserver.loadbalancer.server.port=4000"
      # HTTP router with redirect middleware
      - "traefik.http.routers.webserver-insecure.rule=Host(`kanjer.api.backend.engineering`)"
      - "traefik.http.routers.webserver-insecure.entrypoints=web"
      - "traefik.http.routers.webserver-insecure.middlewares=redirect-to-https"
      # Define the redirect middleware within this service (ensures accessibility)
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    working_dir: /app
    command: ["yarn", "prod:server"]
    restart: unless-stopped